  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml">

    <head>
      <title>Bioenergy Science Center (BESC) Characterization Workshop - Registration</title>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <link rel="stylesheet" type="text/css" href="http://nreldevy.nrel.gov/biomass/cfm/includes/stylesheets/site.css" />
      <link rel="stylesheet" type="text/css" href="http://nreldevy.nrel.gov/biomass/cfm/includes/stylesheets/print.css" media="print" />
      <link rel="stylesheet" type="text/css" href="registration.css" />
      <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
      <script type="text/javascript" src="http://nreldevy.nrel.gov/includes/javascript/jquery/icons.js"></script>
      <script type="text/javascript" src="http://nreldevy.nrel.gov/includes/javascript/jquery/validate/jquery.validate.js"></script>
      <script type="text/javascript"
              src="http://nreldevy.nrel.gov/biomass/cfm/includes/javascript/validation_rules.js">
      </script>
      <script type="text/javascript"
              src="http://nreldevy.nrel.gov/biomass/cfm/includes/javascript/auto_fill.js">
      </script>
    </head>
    <body id="two-column-page" class="workshop-registration-page">
      <div id="wrapper">
        <!--stopindex-->
        <div id="banner">
          <a href="#content"  class="hide">Skip to main content</a>
          <div id="nrelheader"><a href="/"><img width="1000" height="86" alt="NREL - National Renewable Energy Laboratory" src="http://nreldevy.nrel.gov/images/head_nrel.gif" /></a></div>
          <img src="http://nreldevy.nrel.gov/biomass/images/ibrf_header2.gif" width="1000" height="84" border="0" usemap="#headermap" alt=""/>
          <map name="headermap" id="headermap">
            <area shape="rect" coords="6,9,745,60" href="http://nreldevy.nrel.gov/biomass/facilities.html" alt="Integrated Biorefinery Research Facility" />
          </map>
        </div>
        <!--startindex-->
        <div id="content" >